image:
  - Visual Studio 2017


before_build:

  - mkdir extlibs
  - cd extlibs

  - curl -fsSL -o sfml.zip https://www.sfml-dev.org/files/SFML-2.4.2-windows-vc14-64-bit.zip
  - 7z x sfml.zip
  - rename SFML-2.4.2 sfml

  - curl -fsSL -o chaiscript.zip https://github.com/ChaiScript/ChaiScript/archive/develop.zip
  - 7z x chaiscript.zip
  - rename Chaiscript-develop chai

  - cd ..


build_script:

  - mkdir build
  - cd build

  - xcopy /E c:\projects\sqee\extlibs\chai\include\chaiscript c:\projects\sqee\include\chaiscript\

  - cmake c:/projects/sqee -DSFML_ROOT=c:/projects/sqee/extlibs/sfml -G "Visual Studio 15 2017 Win64"
  - cmake --build . --target sqee_testing
