image:
  - Visual Studio 2019


before_build:

  - mkdir extlibs
  - cd extlibs

  - curl -fsSL -o sfml.zip https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip
  - 7z x sfml.zip
  - rename SFML-2.5.1 sfml

  - cd ..


build_script:

  - mkdir build
  - cd build

  - cmake c:/projects/sqee -DCMAKE_PREFIX_PATH=c:/projects/sqee/extlibs/sfml -G "Visual Studio 16 2019" -A x64
  - cmake --build .
  

after_build:

  - 7z a sqee-windows-debug.zip Debug/* libs/dearimgui/Debug/* libs/format/Debug/* libs/lua54cpp/Debug/* testing/Debug/* tests/rpg/Debug/* tests/soko/Debug/*

artifacts:
  - path: build/sqee-windows-debug.zip
    name: sqee-windows-debug
