image:
  - Visual Studio 2019


before_build:

  - cd c:/projects
  - curl -fsSL -o vulkan-sdk.exe https://sdk.lunarg.com/sdk/download/1.2.170.0/windows/VulkanSDK-1.2.170.0-Installer.exe
  - vulkan-sdk.exe /S
  - set VULKAN_SDK=c:/VulkanSDK/1.2.170.0
  - set PATH=c:/VulkanSDK/1.2.170.0/Bin;%PATH%

  - cd c:/projects
  - git clone --depth 1 --branch master https://github.com/SFML/SFML.git
  - cd c:/projects/SFML
  #- cmake . -DBUILD_SHARED_LIBS=False -DSFML_USE_STATIC_STD_LIBS=True -DSFML_BUILD_AUDIO=False -DSFML_BUILD_GRAPHICS=False -DSFML_BUILD_NETWORK=False
  - cmake . -DBUILD_SHARED_LIBS=True -DSFML_USE_STATIC_STD_LIBS=False -DSFML_BUILD_AUDIO=False -DSFML_BUILD_GRAPHICS=False -DSFML_BUILD_NETWORK=False
  - cmake --build . --config Debug

  - cd c:/projects
  - git clone --depth 1 --branch 3.3.4 https://github.com/glfw/glfw.git
  - cd c:/projects/glfw
  #- cmake . -DBUILD_SHARED_LIBS=False -DUSE_MSVC_RUNTIME_LIBRARY_DLL=False -DGLFW_BUILD_DOCS=False -DGLFW_BUILD_EXAMPLES=False -DGLFW_BUILD_TESTS=False -DCMAKE_INSTALL_PREFIX=.
  - cmake . -DBUILD_SHARED_LIBS=True -DUSE_MSVC_RUNTIME_LIBRARY_DLL=True -DGLFW_BUILD_DOCS=False -DGLFW_BUILD_EXAMPLES=False -DGLFW_BUILD_TESTS=False -DCMAKE_INSTALL_PREFIX=.
  - cmake --build . --config Debug --target install


build_script:

  - cd c:/projects/sqee
  - git submodule update --init --recursive

  - mkdir build
  - cd build

  - cmake .. -DCMAKE_PREFIX_PATH=c:/projects/SFML;c:/projects/glfw -G "Visual Studio 16 2019" -A x64
  - cmake --build . --config Debug


after_build:

  - cd c:/projects/sqee/build
  - 7z a sqee-windows-debug.zip Debug/* libs/dearimgui/Debug/* libs/format/Debug/* libs/wren/Debug/* testing/Debug/* tests/rpg/Debug/* tests/soko/Debug/* tests/vkdemo/Debug/*

artifacts:
  - path: build/sqee-windows-debug.zip
    name: sqee-windows-debug
