dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_script:
  - wget https://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz -O /tmp/sfml.tar.gz
  - tar -xf /tmp/sfml.tar.gz
  - sudo cp -r SFML-2.4.2/* /usr/
  - sudo apt build-dep libsfml -y -q
  - wget https://github.com/ChaiScript/ChaiScript/archive/develop.zip -O /tmp/chaiscript.zip
  - unzip -q /tmp/chaiscript.zip
  - sudo cp -r ChaiScript-develop/include /usr/

script:
  - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake .
  - cmake --build . --
