os: linux
dist: focal
language: cpp

addons:
  apt:
    packages:
      - libsfml-system2.5
      - libsfml-window2.5
      - libsfml-audio2.5
      - libsfml-dev

before_script:
  - \# nothing to do here

script:
  - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake .
  - cmake --build . --
