os: linux
dist: focal
language: cpp

addons:
  apt:
    packages:
      - libsfml-system2.5
      - libsfml-window2.5
      - libsfml-dev

script:
  - cd /home/travis/build/jagoly/sqee
  - cmake .
  - cmake --build .
