os: linux
dist: focal
language: cpp

addons:
  apt:
    packages:
      - libsfml-system2.5
      - libsfml-window2.5
      - libsfml-dev
      - libglfw3-dev

script:
  - cd /home/travis/build/jagoly/sqee

  - wget -O vulkan-sdk.tar.gz https://sdk.lunarg.com/sdk/download/1.2.170.0/linux/vulkansdk-linux-x86_64-1.2.170.0.tar.gz
  - tar -xzf vulkan-sdk.tar.gz
  - source 1.2.170.0/setup-env.sh

  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
