dist: focal
sudo: required
language: cpp

addons:
  apt:
    sources:
    packages:
      - libsfml-system2.5
      - libsfml-window2.5
      - libsfml-audio2.5

before_script:

  - wget https://github.com/ChaiScript/ChaiScript/archive/develop.zip -O /tmp/chaiscript.zip
  - unzip -q /tmp/chaiscript.zip
  - sudo cp -r ChaiScript-develop/include /usr/

script:
  - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake .
  - cmake --build . --
