image:
  - Visual Studio 2019


before_build:

  - mkdir extlibs
  - cd extlibs

  - curl -fsSL -o sfml.zip https://www.sfml-dev.org/files/SFML-2.5.1-windows-vc15-64-bit.zip
  - 7z x sfml.zip
  - rename SFML-2.5.1 sfml

  - curl -fsSL -o chaiscript.zip https://github.com/ChaiScript/ChaiScript/archive/v6.1.0.zip
  - 7z x chaiscript.zip
  - rename Chaiscript-6.1.0 chaiscript

  - cd ..


build_script:

  - mkdir build
  - cd build

  - xcopy /E c:\projects\sqee\extlibs\chaiscript\include\chaiscript c:\projects\sqee\include\chaiscript\

  - cmake c:/projects/sqee -DCMAKE_PREFIX_PATH=c:/projects/sqee/extlibs/sfml -G "Visual Studio 16 2019" -A x64
  - cmake --build . --target sqee
