name: Build

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: latest
        cache: true
        quiet: false

    - name: Install GLFW Dependencies
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev

    - name: Checkout GLFW
      uses: actions/checkout@v3
      with:
        path: glfw
        repository: glfw/glfw
        ref: 3.3.8      

    - name: Configure and Build GLFW
      working-directory: ./glfw
      run: |
        cmake . -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=.
        cmake --build . --target install --config Debug --parallel

    - name: Checkout SQEE
      uses: actions/checkout@v3
      with:
        path: sqee
        submodules: recursive

    - name: Configure and Build SQEE
      working-directory: ./sqee
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_PREFIX_PATH=../glfw
        cmake --build . --config Debug

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  # Execute tests defined by the CMake configuration.  
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C ${{env.BUILD_TYPE}}
