name: Build
on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: latest
        cache: true
        quiet: false

    - name: Install GLFW Dependencies
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev

    - name: Checkout GLFW
      uses: actions/checkout@v3
      with:
        path: glfw
        repository: glfw/glfw
        ref: 3.3.8      

    - name: Configure and Build GLFW
      working-directory: glfw
      run: |
        cmake . -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_SHARED_LIBS=OFF -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=.
        cmake --build . --target install --parallel

    - name: Checkout SQEE
      uses: actions/checkout@v3
      with:
        path: sqee
        submodules: recursive

    - name: Configure and Build SQEE
      working-directory: sqee
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_PREFIX_PATH=../glfw -DSQEE_STATIC_LIB=ON
        cmake --build . --parallel

    - uses: actions/upload-artifact@v3
      with:
        name: sqee-linux-debug
        path: build
